### ISSUE TITLE
Refer to #eubfws2018 question: Is bf LOUD?

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#18]
Before I forget this. There was a slide at this year's European Bibframe workshop we can perfectly take up in the workshop asking "Are these [bf] data really LOUD?"

See https://twitter.com/OsmaSuominen/status/1042047138484641792 & http://www.casalini.it/EBW2018/web_content/2018/presentations/Hubay.pdf, last slide

**Comment by fsteeg** [comment]
I think we can close this, see https://hbz.github.io/swib18-workshop/
