### ISSUE TITLE
Set up Elasticsearch & openly available kibana with complete Loc-instances-Bibframe dataset

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#23]

**Comment by dr0i** [comment]
While the solution provided in a) https://github.com/hbz/lobid-resources/issues/851 is not proper enough but b) https://github.com/hbz/swib18-workshop/issues/2 not fast enough we go again with a) using java-jsonld, facing some issues which must be resolved, see https://github.com/hbz/lobid-resources/issues/940.

**Comment by acka47** [comment]
@dr0i is now able to convert the LOC data with the Java JSON-LD library and the output looks much like what we generate in the workshop. Here is the current status with the same example that we use in the workshop:

- Example record: https://github.com/hbz/lobid-resources/blob/523-addLanguageTagSupport/src/test/resources/jsonld-loc/c000101650
- JSON-LD context: https://github.com/hbz/lobid-resources/blob/523-addLanguageTagSupport/web/conf/context-loc.jsonld

The current differences to the JSON-LD from the workshop (at least those I have found) are: 

- all types have an array (which is intended but we will have to think about whether we actually want it for the LoC data)
- `http://id.loc.gov/ontologies/bflc/EncodingLevel` is mapped to `EncodedLevel` in the context (instead of `EncodingLevel`), see https://github.com/hbz/lobid-resources/blob/523-addLanguageTagSupport/web/conf/context-loc.jsonld#L65 
- `titleSortKey` has an array (`"@container": "@set"` in the context)
- Also, the pending fix for the missing datatypes in the context (https://github.com/hbz/swib18-workshop/pull/30) has to also be implemented in lobid-resources.

**Comment by dr0i** [comment]
Did that. Also indexed a 100k test resources , see `curl  "http://weywot5.hbz-nrw.de:9200/loc_works/_search?q=*" |json_pp`. ETL time was 5 minutes so it takes roughly the same time as the ETL of lobid-resources.

**Comment by acka47** [comment]
Thanks for indexing. Will soon take a look.

> so it takes roughly the same time as the ETL of lobid-resources.

\o/ This is good to hear.

**Comment by acka47** [comment]
Just took a look at the data. Here is what I noticed.

1. Some things are missing in the context as MADS classes are not compacted: `http://www.loc.gov/mads/rdf/v1#ComplexSubject`, `http://www.loc.gov/mads/rdf/v1#GenreForm`, `http://www.loc.gov/mads/rdf/v1#Temporal`, `http://www.loc.gov/mads/rdf/v1#Geographic` etc. also the MADSproperty `http://www.loc.gov/mads/rdf/v1#isMemberOfMADSScheme`. Also some bflc properties: `http://id.loc.gov/ontologies/bflc/consolidates`, `http://id.loc.gov/ontologies/bflc/relatorMatchKey`, `http://id.loc.gov/ontologies/bflc/applicableInstitution` where the first two are also missing in the workshop context (see https://github.com/hbz/swib18-workshop/issues/32).
Why not use the context at https://github.com/hbz/swib18-workshop/blob/master/data/context.json? (It would be easier for me to work with one context anyway.)
2. Kibana is quite helpful for finding other errors. When I got to "Management" -> "Index Patterns" -> select "loc_works" and then filter by `http://` I get all fields with a "http" in them. There are those already noted in 1.) and some more that have in common that they have `"@language": null` in the context at https://github.com/hbz/lobid-resources/blob/523-addLanguageTagSupport/web/conf/context-loc.jsonld

I guess, nearly all errors will be fixed with using the workshop context. The rest will be fixed with https://github.com/hbz/swib18-workshop/issues/32.

**Comment by acka47** [comment]
For documentation: Some records are not indexed in ES because they have no valid date as value of `adminMetadata.changeDate`.

**Comment by acka47** [comment]
BTW, a lessons learned for Kibana: At "Management" -> "index patterns" -> "loc_works" I had to refresh the field list. Otherwise the fields from the previous index would be shown there and also in the field autosuggests for creating a visualization.

**Comment by dr0i** [comment]
@acka47 I indexed loc-works-bibframe with the workshop's json-context. You have to set the index-alias to use it for kibana. 3k more documents are missing now, you will get tomorrow morning the lobid-admin mail complaining about `[MapperParsingException[object mapping for [language] tried to parse field [null]` and some more for `subject` etc. and the known `adminMetadata.changeDate`.

**Comment by acka47** [comment]
Taking a look at the new index, some of the property/type URIs are now compacted but some others are still missing:

- [x] `http://www.loc.gov/mads/rdf/v1#ComplexSubject`
- [x] `http://www.loc.gov/mads/rdf/v1#GenreForm` -> missing in context as there is also `bf:GenreForm`
- [x] `http://www.loc.gov/mads/rdf/v1#Temporal` -> missing in context as there is also `bf:Temporal`
- [x] `http://www.loc.gov/mads/rdf/v1#Geographic` 
- [ ] `http://www.loc.gov/mads/rdf/v1#isMemberOfMADSScheme`
- [ ] `http://id.loc.gov/ontologies/bflc/consolidates`
- [ ] `http://id.loc.gov/ontologies/bflc/relatorMatchKey`
- [x]  `http://id.loc.gov/ontologies/bflc/applicableInstitution`

For `bflc:consolidates` and `bflc:relatorMatchKey` see https://github.com/hbz/swib18-workshop/issues/32#issue-380149286. I also found the problem with `mads:GenreForm` and `mads:Temporal`. What I do not understand is why `mads:isMemberOfMADSScheme` is not compacted as it is in the current context, see https://github.com/hbz/swib18-workshop/blob/master/data/context.json#L1114

**Comment by acka47** [comment]
Closing this one as index and Kibana are up. The data may not be perfect but it is totally fine for an experimental setup.
