### ISSUE TITLE
Add LOUD slide and reference

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#28]
...with reference to Rob.

**Comment by acka47** [comment]
I think we should also add the quote "The API is the developers' user interface". Or we could refer to the guide Rob mentions that speaks of "Developer empathy": https://apiguide.readthedocs.io/en/latest/principles/empathy.html

**Comment by fsteeg** [comment]
I think we can close this, see https://hbz.github.io/swib18-workshop/
