### ISSUE TITLE
Some property/type URIs are not compacted

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#32]
~Two~ Some bflc properties are missing in the context because they are missing in the [BFLC vocabulary](http://id.loc.gov/ontologies/bflc.html) so that they were not added to the context with f6fab69b5d0896714fd0ee5368834c944b299de7:
- `http://id.loc.gov/ontologies/bflc/consolidates`
- `http://id.loc.gov/ontologies/bflc/relatorMatchKey` 
- `http://id.loc.gov/ontologies/bflc/procInfo`
- `http://id.loc.gov/ontologies/bflc/profile`

**Comment by acka47** [comment]
Another property that is not compacted is `http://id.loc.gov/ontologies/bibframe/relatedTo`. I think it wasn't added because the python script does not seem to cover properties that are of type `owl:SymmetricProperty`. Thus, the following four properties are also missing (but I am not sure whether they are actually used in the dataset): `bf:issuedWith`, `bf:otherEdition`, `bf:otherPhysicalFormat`, `bf:hasEquivalent`,

**Comment by acka47** [comment]
`bf:relatedTo` was added to the context. `bf:otherPhysicalFormat` and `bf:hasEquivalent` are not used in the dataset. The following are still missing in the context:

- `bf:issuedWith`
- `bf:otherEdition`
- `http://id.loc.gov/ontologies/bflc/consolidates`
- `http://id.loc.gov/ontologies/bflc/relatorMatchKey` 
- `http://id.loc.gov/ontologies/bflc/procInfo`
- `http://id.loc.gov/ontologies/bflc/profile`

**Comment by acka47** [comment]
Also, there are lots of properties not compacted, which actually should be as they are in the context. Examples: `arrangement.http://id.loc.gov/ontologies/bflc/appliesTo`, `http://id.loc.gov/ontologies/bibframe/projection`. See the whole list in the index profile in Kibana by filtering with "http".

**Comment by kirkhess** [comment]
These ones resolve:
http://id.loc.gov/ontologies/bflc/procInfo
http://id.loc.gov/ontologies/bflc/profile
http://id.loc.gov/ontologies/bibframe/issuedWith & otherEdition.

http://id.loc.gov/ontologies/bflc/consolidates is not used in the converter currently - I'm not sure where that one came from. We'll look into relatorMatchKey.

**Comment by acka47** [comment]
@kirkhess Yes, only those do not resolve that are listed in https://github.com/lcnetdev/bibframe-ontology/issues/48.

**Comment by acka47** [comment]
Won't fix. It makes sense (for the workshop and ELAG bootcamp) to still have some examples in the data that don't work that well.
