### ISSUE TITLE
Collecting feedback on LoC dataset

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#33]
In this issue we collect things (errors, bugs, things that might be improved) we noticed in the LoC's Bibframe dataset.

- `contribution` array is not an ordered list
- Some properties are used where the URIs don't resolve, see https://github.com/hbz/swib18-workshop/issues/32#issue-380149286
- It would be nice if LoC provided a JSON-LD context for the dataset

**Comment by acka47** [comment]
There are redundancies between classes in the [MADS](http://www.loc.gov/mads/rdf/v1) and [Bibframe](http://id.loc.gov/ontologies/bibframe/) vocabularies which both are used:

- `bf:GenreForm` and `mads:GenreForm`
- `bf:Temporal` and `mads:Temporal`
- `bf:Topic` and `mads:Topic`

**Comment by acka47** [comment]
The wrong URI is used for `mads:isMemberOfMADSScheme`, it should be `http://www.loc.gov/mads/rdf/v1#isMemberOfMADSScheme` but is `http://www.loc.gov/mads/rdf/v1#isMemberofMADSScheme` (with lower case "o")

**Comment by acka47** [comment]
Instead of the correct `http://id.loc.gov/ontologies/bibframe/instrumentalType` the following is used: `http://id.loc.gov/ontologies/bibframe/instrumentType`

**Comment by kirkhess** [comment]
Thank you for the comments - I wanted to reply about the context question. The BIBFRAME editor uses this context:
"@context": {
  "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
  "xsd": "http://www.w3.org/2001/XMLSchema#",
  "bf": "http://id.loc.gov/ontologies/bibframe/",
  "bflc": "http://id.loc.gov/ontologies/bflc/",
  "madsrdf": "http://www.loc.gov/mads/rdf/v1#",
  "pmo": "http://performedmusicontology.org/ontology/"
 },

We can publish this context but I think you were suggesting a specific way to do it? We put our documentation on http://www.loc.gov/bibframe so by default we'd probably put it there unless you have another suggestion. 

For your issues, we are tracking issues here: 
https://github.com/lcnetdev/bibframe-ontology/issues

Thanks!
Kirk Hess
LC

**Comment by acka47** [comment]
Thanks for the response, Kirk. You are right that we are thinking about a more elaborate context. The one you provide is basically declaring namespace prefixes so that JSON keys won't be URIs but e.g. `"bf:contribution"`. But the JSON-LD context can provide much more to make the actual JSON-LD data better to read and to work with. I provide some examples in the [blog post](the-json-ld-context):

> For example with the line `"label": "http://www.w3.org/2000/01/rdf-schema#label"` in the context, I can now use the key `"label"` in a JSON-LD document and when including the context in the document (for example by referencing it like `"@context": "https://example.org/context.jsonld"`) the key-value pair can be translated to an RDF triple. The context is also used to declare that the values of a specific key should be interpreted as URIs (by saying `"@type": "@id"`) or as a date ([example](https://github.com/hbz/swib18-workshop/blob/85b3d87d2d3d18f7f435a617a3e8b7c104b56b3f/data/context.json#L139-L142)) or to enforce that a key always is used with an array (`"@container": "@set"`), see e.g [here](https://github.com/hbz/swib18-workshop/blob/85b3d87d2d3d18f7f435a617a3e8b7c104b56b3f/data/context.json#L263-L267).

See the context we created to get a picture of what we have in mind: https://github.com/hbz/swib18-workshop/blob/master/data/context.json Though we already have a context to use in our project and do not have the need for it right now, it would be great in my opinion if LoC would provided kind of a "canonical" context for the dataset for others to use.

**Comment by acka47** [comment]
@kirkhess I opened two issues in the Bibframe ontology repo. As the other issues refer to the Bibframe works dataset published in May/June 2018, I guess  https://github.com/lcnetdev/bibframe-ontology/issues is not the right place to address those, is it?

**Comment by acka47** [comment]
Closing as the feedback was submitted to LoC.
