### ISSUE TITLE
Publish JSON-LD context

### ISSUE THREAD

**Issue by acka47** [hbz/swib18-workshop#43]
Currently, it says in the data `"@context": "http://lobid.org/resources/loc-context.jsonld"` but at http://lobid.org/resources/loc-context.jsonld there is no context document. @dr0i, please publish the [context](https://github.com/hbz/swib18-workshop/blob/master/data/context.json) at http://labs.lobid.org/loc_works/context.jsonld and redirect to this place from http://lobid.org/resources/loc-context.jsonld.

**Comment by dr0i** [comment]
Doing it with apache:
rewrite to labs, reverseProxy to http://raw.githubusercontent.com/hbz/lobid-resources/master/web/conf/context-loc.jsonld.

**Comment by acka47** [comment]
Works like a charm. Thanks! Closing.
