### ISSUE TITLE
Merge into hbz/slides

### ISSUE THREAD

**Issue by dr0i** [hbz/swib18-workshop#44]
Dear fellows,

I find it counterintuitive to have an extra repo for these slides while having a slides repo at  https://github.com/hbz/slides. E.g. took me some time (thx @acka47 !) to find it at all!

So my proposal is to merge it into `hbz/slides` and delete this repo.
What do you think?

**Comment by acka47** [comment]
This is more than just slides but also data, code, docker files etc. I think it was/is much better for the participants to work with. So :-1: from me.

We are collecting all the slides at http://slides.lobid.org/. There you can see from the link where the respective repo is located. Perhaps this will make it easier for you next time. @fsteeg, if you second this, please close the issue.
